// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// C_get_altrep_data1
SEXP C_get_altrep_data1(SEXP x);
RcppExport SEXP _AltrepPointer_C_get_altrep_data1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_get_altrep_data1(x));
    return rcpp_result_gen;
END_RCPP
}
// C_get_altrep_data2
SEXP C_get_altrep_data2(SEXP x);
RcppExport SEXP _AltrepPointer_C_get_altrep_data2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_get_altrep_data2(x));
    return rcpp_result_gen;
END_RCPP
}
// C_create_altrep
SEXP C_create_altrep(SEXP x, SEXP state, SEXP attrName, SEXP attributes);
RcppExport SEXP _AltrepPointer_C_create_altrep(SEXP xSEXP, SEXP stateSEXP, SEXP attrNameSEXP, SEXP attributesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type state(stateSEXP);
    Rcpp::traits::input_parameter< SEXP >::type attrName(attrNameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type attributes(attributesSEXP);
    rcpp_result_gen = Rcpp::wrap(C_create_altrep(x, state, attrName, attributes));
    return rcpp_result_gen;
END_RCPP
}
// C_get_finalizer
SEXP C_get_finalizer(SEXP Extptr, SEXP operation, SEXP dataType);
RcppExport SEXP _AltrepPointer_C_get_finalizer(SEXP ExtptrSEXP, SEXP operationSEXP, SEXP dataTypeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type Extptr(ExtptrSEXP);
    Rcpp::traits::input_parameter< SEXP >::type operation(operationSEXP);
    Rcpp::traits::input_parameter< SEXP >::type dataType(dataTypeSEXP);
    rcpp_result_gen = Rcpp::wrap(C_get_finalizer(Extptr, operation, dataType));
    return rcpp_result_gen;
END_RCPP
}
// C_attachAttr
void C_attachAttr(SEXP R_source, SEXP R_tag, SEXP R_attr);
RcppExport SEXP _AltrepPointer_C_attachAttr(SEXP R_sourceSEXP, SEXP R_tagSEXP, SEXP R_attrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type R_source(R_sourceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_tag(R_tagSEXP);
    Rcpp::traits::input_parameter< SEXP >::type R_attr(R_attrSEXP);
    C_attachAttr(R_source, R_tag, R_attr);
    return R_NilValue;
END_RCPP
}
// C_format_length
SEXP C_format_length(R_xlen_t length);
RcppExport SEXP _AltrepPointer_C_format_length(SEXP lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< R_xlen_t >::type length(lengthSEXP);
    rcpp_result_gen = Rcpp::wrap(C_format_length(length));
    return rcpp_result_gen;
END_RCPP
}
// C_set_duplicate_method
void C_set_duplicate_method(SEXP x, SEXP value);
RcppExport SEXP _AltrepPointer_C_set_duplicate_method(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    C_set_duplicate_method(x, value);
    return R_NilValue;
END_RCPP
}
// C_set_coerce_method
void C_set_coerce_method(SEXP x, SEXP value);
RcppExport SEXP _AltrepPointer_C_set_coerce_method(SEXP xSEXP, SEXP valueSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    Rcpp::traits::input_parameter< SEXP >::type value(valueSEXP);
    C_set_coerce_method(x, value);
    return R_NilValue;
END_RCPP
}
// C_reset_reference_count
SEXP C_reset_reference_count(SEXP env, SEXP var_name, SEXP x);
RcppExport SEXP _AltrepPointer_C_reset_reference_count(SEXP envSEXP, SEXP var_nameSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type env(envSEXP);
    Rcpp::traits::input_parameter< SEXP >::type var_name(var_nameSEXP);
    Rcpp::traits::input_parameter< SEXP >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(C_reset_reference_count(env, var_name, x));
    return rcpp_result_gen;
END_RCPP
}
// test_logical
SEXP test_logical(int len);
RcppExport SEXP _AltrepPointer_test_logical(SEXP lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    rcpp_result_gen = Rcpp::wrap(test_logical(len));
    return rcpp_result_gen;
END_RCPP
}
// test_int
SEXP test_int(int len);
RcppExport SEXP _AltrepPointer_test_int(SEXP lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    rcpp_result_gen = Rcpp::wrap(test_int(len));
    return rcpp_result_gen;
END_RCPP
}
// test_real
SEXP test_real(int len);
RcppExport SEXP _AltrepPointer_test_real(SEXP lenSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type len(lenSEXP);
    rcpp_result_gen = Rcpp::wrap(test_real(len));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _AltrepPointer_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AltrepPointer_C_get_altrep_data1", (DL_FUNC) &_AltrepPointer_C_get_altrep_data1, 1},
    {"_AltrepPointer_C_get_altrep_data2", (DL_FUNC) &_AltrepPointer_C_get_altrep_data2, 1},
    {"_AltrepPointer_C_create_altrep", (DL_FUNC) &_AltrepPointer_C_create_altrep, 4},
    {"_AltrepPointer_C_get_finalizer", (DL_FUNC) &_AltrepPointer_C_get_finalizer, 3},
    {"_AltrepPointer_C_attachAttr", (DL_FUNC) &_AltrepPointer_C_attachAttr, 3},
    {"_AltrepPointer_C_format_length", (DL_FUNC) &_AltrepPointer_C_format_length, 1},
    {"_AltrepPointer_C_set_duplicate_method", (DL_FUNC) &_AltrepPointer_C_set_duplicate_method, 2},
    {"_AltrepPointer_C_set_coerce_method", (DL_FUNC) &_AltrepPointer_C_set_coerce_method, 2},
    {"_AltrepPointer_C_reset_reference_count", (DL_FUNC) &_AltrepPointer_C_reset_reference_count, 3},
    {"_AltrepPointer_test_logical", (DL_FUNC) &_AltrepPointer_test_logical, 1},
    {"_AltrepPointer_test_int", (DL_FUNC) &_AltrepPointer_test_int, 1},
    {"_AltrepPointer_test_real", (DL_FUNC) &_AltrepPointer_test_real, 1},
    {"_AltrepPointer_rcpp_hello_world", (DL_FUNC) &_AltrepPointer_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

void init_raw_class(DllInfo* dll);
void init_logical_class(DllInfo* dll);
void init_integer_class(DllInfo* dll);
void init_real_class(DllInfo* dll);
RcppExport void R_init_AltrepPointer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    init_raw_class(dll);
    init_logical_class(dll);
    init_integer_class(dll);
    init_real_class(dll);
}
