# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_get_altrep_data1 <- function(x) {
    .Call(`_AltrepPointer_C_get_altrep_data1`, x)
}

C_get_altrep_data2 <- function(x) {
    .Call(`_AltrepPointer_C_get_altrep_data2`, x)
}

C_create_altrep <- function(x, state) {
    .Call(`_AltrepPointer_C_create_altrep`, x, state)
}

C_get_finalizer <- function(Extptr, operation, dataType) {
    .Call(`_AltrepPointer_C_get_finalizer`, Extptr, operation, dataType)
}

C_attachAttr <- function(R_source, R_tag, R_attr) {
    invisible(.Call(`_AltrepPointer_C_attachAttr`, R_source, R_tag, R_attr))
}

C_format_lenght <- function(length) {
    .Call(`_AltrepPointer_C_format_lenght`, length)
}

C_set_duplicate_method <- function(x, value) {
    invisible(.Call(`_AltrepPointer_C_set_duplicate_method`, x, value))
}

C_set_coerce_method <- function(x, value) {
    invisible(.Call(`_AltrepPointer_C_set_coerce_method`, x, value))
}

C_set_reference_count <- function(x, count) {
    invisible(.Call(`_AltrepPointer_C_set_reference_count`, x, count))
}

test_int <- function(len) {
    .Call(`_AltrepPointer_test_int`, len)
}

test_logical <- function(len) {
    .Call(`_AltrepPointer_test_logical`, len)
}

rcpp_hello_world <- function() {
    .Call(`_AltrepPointer_rcpp_hello_world`)
}

